### PR TITLE
binds for ZeroMQ4

### PR DESCRIPTION
**Pull request by mosconi**
Based on your previous work, I made a port of the zeromq4 bindings.  I would like to make it available through CPAN.

### CODE REVIEW

**Comment by zmughal** [comment]
Hi, I'm working on making this all build on Windows with an Alien package. RIght now `Alien::ZMQ` only installs `libzmq-3.x`. Would it make sense to make an `Alien::ZMQ4`?

**Comment by mosconi** [comment]
Yes, zeromq 4 has new features like authentication and encryption.

**Comment by zmughal** [comment]
Excellent. I can work out something very soon. :-)

**Comment by lestrrat** [comment]
This PR is still open? @mosconi you are a collaborator on this project as of last september, so you can go ahead and merge this if you want.

**Comment by mosconi** [comment]
The missing merge...

**Pull request merged**
